### ISSUE TITLE
Unresolved bug

### ISSUE THREAD

**Issue by BeichenDream** [trustedsec/COFFLoader#2]
I saw your update, but when I use Visual Studio 2019 to compile and execute, it still has the bug of the previous problem.

**Comment by kev169** [comment]
I tested and verified with Visual Studio 2017, is the output of everything still the same as your previous issue?

**Comment by BeichenDream** [comment]
Same as last issue

**Comment by kev169** [comment]
For 32-bit, 64-bit, or both?

**Comment by BeichenDream** [comment]
x32

**Comment by kev169** [comment]
How are you building the test object file? Mingw or with cl.exe?

**Comment by BeichenDream** [comment]
Mingw

**Comment by kev169** [comment]
Sorry, but I'm having trouble duplicating the problem. Can you send me the version of the mingw compiler you're using for the BOF?

**Comment by BeichenDream** [comment]
root@kali:~# i686-w64-mingw32-gcc -v
Using built-in specs.
COLLECT_GCC=i686-w64-mingw32-gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/i686-w64-mingw32/10-win32/lto-wrapper
Target: i686-w64-mingw32
Configured with: ../../src/configure --build=x86_64-linux-gnu --prefix=/usr --includedir='/usr/include' --mandir='/usr/share/man' --infodir='/usr/share/info' --sysconfdir=/etc --localstatedir=/var --disable-option-checking --disable-silent-rules --libdir='/usr/lib/x86_64-linux-gnu' --libexecdir='/usr/lib/x86_64-linux-gnu' --disable-maintainer-mode --disable-dependency-tracking --prefix=/usr --enable-shared --enable-static --disable-multilib --with-system-zlib --libexecdir=/usr/lib --without-included-gettext --libdir=/usr/lib --enable-libstdcxx-time=yes --with-tune=generic --with-headers=/usr/i686-w64-mingw32/include --enable-version-specific-runtime-libs --enable-fully-dynamic-string --enable-libgomp --enable-languages=c,c++,fortran,objc,obj-c++,ada --enable-lto --enable-threads=win32 --program-suffix=-win32 --program-prefix=i686-w64-mingw32- --target=i686-w64-mingw32 --with-as=/usr/bin/i686-w64-mingw32-as --with-ld=/usr/bin/i686-w64-mingw32-ld --enable-libatomic --enable-libstdcxx-filesystem-ts=yes --enable-dependency-tracking --disable-sjlj-exceptions --with-dwarf2
Thread model: win32
Supported LTO compression algorithms: zlib
gcc version 10-win32 20210110 (GCC)

**Comment by BeichenDream** [comment]
After debugging, I found that this is because Visual Studio will define LoadLibrary as LoadLibraryW when UNICODE is turned on. I have added the patch and you can merge it now.

![1](https://user-images.githubusercontent.com/43266206/109609368-33bf7c80-7b66-11eb-9b02-20667f6a3b13.jpg)
![2](https://user-images.githubusercontent.com/43266206/109609394-3ae68a80-7b66-11eb-875e-40e39e530c1f.jpg)

**Comment by BeichenDream** [comment]
It is now ready to complete the work. Thank you for your excellent writing

![ok](https://user-images.githubusercontent.com/43266206/109611359-13dd8800-7b69-11eb-83b3-e7a8bb25738e.jpg)

**Comment by kev169** [comment]
Ok, changed COFFLoader.c to explicitly call LoadLibraryA e83c8892c9167bf11261fff8fc839ee13fe30902 I'll leave the issue open until I hear back if that's what your change was. Thanks.

**Comment by BeichenDream** [comment]
![num1](https://user-images.githubusercontent.com/43266206/109678394-8b390900-7bb5-11eb-9657-aea0f716c47b.jpg)
Doesn't this refer to the function address? Why write like this
```
                /* This is Type == IMAGE_REL_I386_DIR32 relocation code */
                memcpy(functionMapping + (functionMappingCount * 4), &funcptrlocation, sizeof(uint32_t));
                offsetvalue = (int32_t)(functionMapping + (functionMappingCount * 4));
                memcpy(sectionMapping[counter] + coff_reloc_ptr->VirtualAddress, &offsetvalue, sizeof(uint32_t));
                functionMappingCount++;
```
Instead of this

```
                /* This is Type == IMAGE_REL_I386_DIR32 relocation code */
                memcpy(sectionMapping[counter] + coff_reloc_ptr->VirtualAddress, &funcptrlocation, sizeof(uint32_t));
```

**Comment by kev169** [comment]
Nope, if I remember right the code using that relocation type needed an address that held the pointer to the function, so I store the pointer, and then patch in the address of that pointer into the function. I take it the LoadLibrary -> LoadLibraryA change was correct then? If so I'll close this issue.

**Comment by BeichenDream** [comment]
There is no problem, now it can be closed

**Comment by kev169** [comment]
Ok, thanks. Will close now.
